---
title: "Exercise Data"
author: "IMSOHYUN"
date: "2019년 3월 21일"
output: word_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(gridExtra)
library(grid)

setwd("C:/Users/user/Desktop/I/ewha2/Graphics")
```


# Data
```{r warning=FALSE}
data.f <- read.csv('HW3data.csv')
data <- read_csv("HW3data.csv", col_types = cols(.default = col_double()) )
data[,1] <- data.f[,1] ; data[,2] <- data.f[,2]
data
```


# Data
```{r warning=FALSE}
gg1 <- data %>% select(2,3,4,5) %>%
  gather(starts_with("Var"), key="when",value="value")
p1 <- ggplot(gg1, aes(when,value,fill=Group)) + 
  geom_boxplot() + xlab("") + guides(fill=FALSE) 
  
gg2 <- data %>% select(2,9,10,11) %>%
  gather(starts_with("002"), key="when",value="value")
p2 <- ggplot(gg2, aes(when,value,fill=Group)) + guides(fill=FALSE) +
  geom_boxplot() + xlab("") 

gg3 <- data %>% select(2,15,16) %>%
  gather(starts_with("Var"), key="when",value="value")
p3 <- ggplot(gg3, aes(when,value,fill=Group)) + 
  geom_boxplot() + xlab("") + guides(fill=FALSE) 

grid.arrange(p1, p2, p3, ncol=3,
             top = textGrob("Difference of basic exercise / high intensity exercise",gp=gpar(fontsize=10, font=2)))
```


# Data
```{r warning=FALSE}
g1 <- data %>% select(Group,starts_with("Var_A3")) %>%
  gather(starts_with("Var_A3"), key="when",value="value") %>%
  mutate(week = ifelse(substr(when,nchar(when)-4,nchar(when))=="(0wk)","0wk","8wk"))

ggplot(g1, aes(when,value,fill = week)) +
  geom_boxplot() +
  coord_flip() +
  ggtitle("Var_A3 : 1hr exercise before/after") +
  xlab("") +
  facet_grid(Group ~ .)  +
  scale_x_discrete(limits=c("Var_A3_tread_after_V4(8wk)","Var_A3_V4(8wk)",
                            "Var_A3_tread_after_V2(0wk)","Var_A3_V2(0wk)"))

g2 <- data %>% select(Group,starts_with("Var_A1")) %>%
  gather(starts_with("Var_A1"), key="when",value="value") %>%
  mutate(week = ifelse(substr(when,nchar(when)-4,nchar(when))=="(0wk)","0wk",
                       ifelse(substr(when,nchar(when)-3,nchar(when))=="2wk)","-2wk","8wk")))

ggplot(g2, aes(when,value, fill = week)) +
  geom_boxplot() +
  coord_flip() +
  ggtitle("Var_A1 : 1hr exercise before/after") +
  xlab("") +
  facet_grid(Group ~ .) +
  scale_x_discrete(limits=c("Var_A1_tread_after_V4(8wk)","Var_A1_V4(8wk)",
                            "Var_A1_tread_after_V2(0wk)","Var_A1_V2(0wk)",
                            "Var_A1_tread_after_V1(-2wk)","Var_A1_V1(-2wk)"))

g3 <- data %>% select(Group,starts_with("002")) %>%
  gather(starts_with("002"), key="when",value="value") %>%
  mutate(week = ifelse(substr(when,nchar(when)-4,nchar(when))=="(0wk)","0wk",
                       ifelse(substr(when,nchar(when)-3,nchar(when))=="2wk)","-2wk","8wk")))

ggplot(g3, aes(when,value, fill = week, na.rm=TRUE)) +
  geom_boxplot() +
  coord_flip() +
  ggtitle("002_A2 : 1hr exercise before/after") +
  xlab("") +
  facet_grid(Group ~ .) +
  scale_x_discrete(limits=c("002_A2_tread_after_V4(8wk)","002_A2_V4(8wk)",
                            "002_A2_tread_after_V2(0wk)","002_A2_V2(0wk)",
                            "002_A2_tread_after_V1(-2wk)","002_A2_V1(-2wk)"))
```


# Data
```{r warning=FALSE}

```