---
title: "Part2 - Wrangle"
author: "IMSOHYUN"
date: "2019년 3월 14일"
output: word_document
---

```{r setup, warning=FALSE}
library("tidyverse")
diamonds
```


# 1.
```{r warning=FALSE}
quantile(diamonds$x)
quantile(diamonds$y)
quantile(diamonds$z)

diamonds %>%
  mutate(id = row_number()) %>%
  select(x, y, z, id) %>%
  gather(variable, value, -id) %>%
  ggplot(aes(x = value)) +
  geom_density() +
  facet_grid(variable ~ .)
```


# 2.
```{r warning=FALSE}
ggplot(diamonds, aes(x = price)) + geom_histogram(binwidth = 10)
ggplot(filter(diamonds, price < 2000), aes(x = price)) +
  geom_histogram(binwidth = 10)
ggplot(filter(diamonds, price < 700), aes(x = price)) +
  geom_histogram(binwidth = 10)
```


# 3.
```{r warning=FALSE}
diamonds %>%
  filter(carat >= 0.99, carat <= 1) %>% count(carat)
```


# 4.
```{r warning=FALSE}
ggplot(diamonds, aes(color = cut_number(carat, 5), x = price)) +
  geom_freqpoly() +
  labs(x = "Price", y = "Count", color = "Carat")

ggplot(diamonds, aes(color = cut_width(carat, 1, boundary = 0), x = price)) +
  geom_freqpoly() +
  labs(x = "Price", y = "Count", color = "Carat")
```


# 5.
```{r warning=FALSE}
ggplot(diamonds, aes(x = cut_number(price, 10), y = carat)) +
  geom_boxplot() +
  coord_flip() +
  xlab("Price")
```


# 6.
```{r warning=FALSE}
ggplot(diamonds) + geom_point(aes(carat,price))
```


# 7. 

# (1)
```{r warning=FALSE}
table2

cases <- filter(table2, type == "cases") %>%
  rename(cases = count) %>% select(country, year, cases) %>%
  arrange(country, year)
cases
```


# (2)
```{r warning=FALSE}
population <- filter(table2, type == "population") %>%
  rename(population = count) %>% select(country, year, population) %>%
  arrange(country, year)
population
```


# (3)
```{r warning=FALSE}
table4a
table4b

table4c <-
  tibble(
    country = table4a$country,
    `1999` = table4a[["1999"]] / table4b[["1999"]] * 10000,
    `2000` = table4a[["2000"]] / table4b[["2000"]] * 10000
  )
table4c
```


# 8.
```{r warning=FALSE}
stocks <- tibble(
  year = c(2015, 2015, 2016, 2016),
  half = c(1, 2, 1, 2),
  return = c(1.88, 0.59, 0.92, 0.17)
)
stocks 
```


```{r warning=FALSE}
stocks %>%
  spread(year, return) 

stocks %>%
  spread(year, return) %>%
  gather(`2015`:`2016`, key = "year", value = "return")
```


# 9
```{r warning=FALSE}
preg <- tribble(
  ~pregnant, ~male, ~female,
  "yes", NA, 10,
  "no", 20, 12
)
preg
```

```{r warning=FALSE}
preg %>%
  spread(male,pregnant)

preg %>%
  spread(pregnant,male)
```

```{r warning=FALSE}
preg %>%
  gather(male, female, key = "sex", value = "count")
```